### ISSUE TITLE
How-to extract FMP files?

### ISSUE THREAD

**Issue by raxpww** [aresta/ESP32_GPS#3]
Good day. Interesting project and thanks for your work. Please describe the step-by-step process of how exactly you get FMP map files from PBF. There are no working instructions at the link https://github.com/aresta/OSM_Extract, the extract_features.py script works with an error and does nothing. Perhaps you have fixed it and have working versions?

**Comment by aresta** [comment]
Hi, I have added a brief explanation in the readme. It is still work in progress and the system is quite manual and not very convenient. It's just for testing, it will need some work to make it more user friendly.
Try and if you have question put it here, I'll try to help when I can.
Thank you!
