### ISSUE TITLE
Tracking support

### ISSUE THREAD

**Issue by lodesmets** [aresta/ESP32_GPS#4]
Hey, 

This looks like a nice project. I ordered the components to create it. I have 2 ideas:
- support tracking (create GPX file with waypoints, so you can export your activity)
- showing the route: load in an GPX file and show the route on the map

I will start to work on the first one (first read the GPX standards) while I wait for the components to arrive

**Comment by aresta** [comment]
If you need anything just ask. Now I'm busy with other topics but I'll continue with it.
Enjoy it!
