### ISSUE TITLE
env.h

### ISSUE THREAD

**Issue by lodesmets** [aresta/ESP32_GPS#6]
Hey,

I almost got it working, but how do you get the INIT_POS in env.h?

235664.91, 5074788.07 // Tibidabo

Those aren't lon and lat. So how did you get those points?

**Comment by aleonnet** [comment]
Hi,
I passed through this and I think it's kind of unusual to use mercator x, y as inputs, but you can convert your lat/lng using this code snippet on gps.cpp file:

`#define DEG2RAD(a)   ((a) / (180 / M_PI))
#define RAD2DEG(a)   ((a) * (180 / M_PI))
#define EARTH_RADIUS 6378137
double lat2y(double lat) { return log(tan( DEG2RAD(lat) / 2 + M_PI/4 )) * EARTH_RADIUS; }
double lon2x(double lon) { return          DEG2RAD(lon)                 * EARTH_RADIUS; }`


Also, if you want to try it on python:

`import math

# Constants
EARTH_RADIUS = 6378137  # Earth's radius in meters

# Functions for conversion
def DEG2RAD(degrees):
    """Convert degrees to radians."""
    return degrees * (math.pi / 180)

def lat2y(lat):
    """Convert latitude to Mercator y-coordinate."""
    return math.log(math.tan(DEG2RAD(lat) / 2 + math.pi / 4)) * EARTH_RADIUS

def lon2x(lon):
    """Convert longitude to Mercator x-coordinate."""
    return DEG2RAD(lon) * EARTH_RADIUS

# Coordinates
latitude = 41.4225
longitude = 2.118611

# Convert to Mercator coordinates
mercator_x = lon2x(longitude)
mercator_y = lat2y(latitude)

print(mercator_x, mercator_y)`

I tried Aresta's approach on a T-Display-S3-Pro and I got interesting results. Now I'm trying a different approach on my spare time, directly decoding vector tiles from .mvt files and let's see how S3 performs. This could potentially bypass that Extraction process.

**Comment by aresta** [comment]
Yes, correct.
With this online map tool you can translate the coordinates:
https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=1.011695,48.123893,4.165016,49.399566&tab=2
In the tab 'PC' or 'CD' at the right, you get the coordinates in the different formats: EPSG:3857 or EPSG:4326 (lat,lon)
