### ISSUE TITLE
Max Zoom

### ISSUE THREAD

**Issue by jgauchia** [aresta/ESP32_GPS#8]
Hi, 
I've a question

What is the max zoom that can display?
Actually zoom great than 4 crashed

Thank you!

**Comment by aresta** [comment]
Hi, sorry, I was a bit disconnected the last weeks.
 Regarding the zoom, it should work until 7, I think.  What could happen is that when there are a lot of objects, for example in the middle of a city, and you zoom out maybe you get out of memory.  It shouldn't happen, but it's not tested a lot.

Another possible problem is when you are close to the end of the area of your maps. If you zoom out, some portions of the screen will be out of the maps, and could be that some functions don't manage it properly and crash.  I remember some effect like that, it should be investigated and fixed/prevented in the code.

Let me know more details of error, and we can check.
Thank you!

**Comment by jgauchia** [comment]
Hi!
No problem, You know i've implemented in my project your solution for vectorial maps, maybe was a mistake in my code... sorry
Thank you!

(Ja comentem, no hi ha problema, es per saber-ho :P )

**Comment by aresta** [comment]
Cap problema :)

Check in your code when it has some parts out of the map files. Then the function read_map_block or equivalent probably return null.

**Comment by jgauchia** [comment]
Ok, no problem , thank you!
